name: Test JSEQ scRNA-seq

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull JSEQ Docker image
        run: |
          docker pull jkubis96/jseq_scrnaseq:latest
          id=$(docker images --format "{{.ID}}" jkubis96/jseq_scrnaseq:latest)
          echo "Using image ID: $id"

          chmod -R +x ${{ github.workspace }}/scripts

          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -e fun_run=Test \
            "$id" \
            /app/scripts/docker
